// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package weatherserver;

public final class RainfallSensorSocket_Stub
    extends java.rmi.server.RemoteStub
    implements weatherserver.WeatherRMI, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getMeasurement_0;
    
    static {
	try {
	    $method_getMeasurement_0 = weatherserver.WeatherRMI.class.getMethod("getMeasurement", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public RainfallSensorSocket_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getMeasurement()
    public java.lang.String getMeasurement()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getMeasurement_0, null, -219544199377205194L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
