// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package weatherclient;

public final class MonitoringStation_Stub
    extends java.rmi.server.RemoteStub
    implements weatherclient.StationRMI, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_alert_0;
    
    static {
	try {
	    $method_alert_0 = weatherclient.StationRMI.class.getMethod("alert", new java.lang.Class[] {java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public MonitoringStation_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of alert(String)
    public void alert(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_alert_0, new java.lang.Object[] {$param_String_1}, -8897669050465004220L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
